# Generated by Django 4.0.2 on 2022-02-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatabase',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='userdatabase',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userdatabase',
            old_name='fname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='userdatabase',
            old_name='lname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='userdatabase',
            old_name='password',
            new_name='Password',
        ),
    ]
