# Generated by Django 4.0.2 on 2022-02-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enquirydatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryDataBase',
        ),
    ]
