# Generated by Django 4.0.2 on 2022-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enquirydatabase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDataBase',
            new_name='AdminDataBase',
        ),
    ]
